CREATE TABLE "embeddings_config" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"base_url" text NOT NULL,
	"model" text NOT NULL,
	"api_kind" text DEFAULT 'openai' NOT NULL,
	"dimensions" integer NOT NULL,
	"header_names" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- pgvector refuses to change a vector column's dimension while incompatible
-- (768-dim) values exist, so clear existing vectors first. Memory *content* is
-- preserved; vectors are regenerated by the "Re-embed all" action in Settings
-- (POST /api/memory/reembed) once an embeddings provider is configured.
UPDATE "memories" SET "embedding" = NULL;--> statement-breakpoint
ALTER TABLE "memories" ALTER COLUMN "embedding" SET DATA TYPE vector(1024);