-- pgvector refuses to change a vector column's dimension while incompatible
-- (1024-dim) values exist, so clear existing vectors first. Memory *content* is
-- preserved; vectors are regenerated by the "Re-embed all" action in Settings
-- (POST /api/memory/reembed) once an embeddings provider is configured.
UPDATE "memories" SET "embedding" = NULL;--> statement-breakpoint
ALTER TABLE "memories" ALTER COLUMN "embedding" SET DATA TYPE vector(1536);